// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLMcYtTaZz5STqFcX7xvrpQRLi0TN2d84',
    appId: '1:505391705786:web:dcf350a39fa207d4ed5c83',
    messagingSenderId: '505391705786',
    projectId: 'billiard-pos-80296',
    authDomain: 'billiard-pos-80296.firebaseapp.com',
    storageBucket: 'billiard-pos-80296.firebasestorage.app',
    measurementId: 'G-FEGV0F2KRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHylmpeIFmeYGZkmccqFqH2uPvVuzJhuU',
    appId: '1:505391705786:android:5f617e97db7d4aa9ed5c83',
    messagingSenderId: '505391705786',
    projectId: 'billiard-pos-80296',
    storageBucket: 'billiard-pos-80296.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3d7r3A_d8Ef73GlYi8E16rVt13LjIVkY',
    appId: '1:505391705786:ios:b7632beccd00497bed5c83',
    messagingSenderId: '505391705786',
    projectId: 'billiard-pos-80296',
    storageBucket: 'billiard-pos-80296.firebasestorage.app',
    iosBundleId: 'com.codingaja.yesbilliard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLMcYtTaZz5STqFcX7xvrpQRLi0TN2d84',
    appId: '1:505391705786:web:a4ff9973cc3d3226ed5c83',
    messagingSenderId: '505391705786',
    projectId: 'billiard-pos-80296',
    authDomain: 'billiard-pos-80296.firebaseapp.com',
    storageBucket: 'billiard-pos-80296.firebasestorage.app',
    measurementId: 'G-0EPV5NH10W',
  );
}
