// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARQoH6f5H-kLaz239_s0BJThcThzalVF4',
    appId: '1:9209034397:web:729afde490e9cad2050674',
    messagingSenderId: '9209034397',
    projectId: 'yesbilliard',
    authDomain: 'yesbilliard.firebaseapp.com',
    storageBucket: 'yesbilliard.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX1ZbDJih52Lhphz9hiGglj9T58N5-vy0',
    appId: '1:9209034397:android:34e17650feb1f013050674',
    messagingSenderId: '9209034397',
    projectId: 'yesbilliard',
    storageBucket: 'yesbilliard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAao8nrBi-fWnPY5Op_VdstBqcrUVK9Yhs',
    appId: '1:9209034397:ios:34bc5ad907497253050674',
    messagingSenderId: '9209034397',
    projectId: 'yesbilliard',
    storageBucket: 'yesbilliard.firebasestorage.app',
    iosBundleId: 'com.codingaja.yesbilliard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARQoH6f5H-kLaz239_s0BJThcThzalVF4',
    appId: '1:9209034397:web:8474608074090eee050674',
    messagingSenderId: '9209034397',
    projectId: 'yesbilliard',
    authDomain: 'yesbilliard.firebaseapp.com',
    storageBucket: 'yesbilliard.firebasestorage.app',
  );
}
